apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - name: simple-api
        image: asia-northeast1-docker.pkg.dev/tomoki-sandbox/my-repo/simple-api:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-lb
spec:
  type: LoadBalancer
  selector:
    app: simple-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
